# Generated by Django 4.2.16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('selection_type', models.CharField(choices=[('fan', '风机选型'), ('cable', '电缆选型'), ('motor', '电机选型'), ('other', '其他')], default='fan', max_length=50, verbose_name='选型类型')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('excel_filename', models.CharField(blank=True, max_length=255, null=True, verbose_name='Excel文件名')),
                ('excel_content', models.TextField(blank=True, null=True, verbose_name='Excel文件内容(Base64)')),
                ('excel_size', models.IntegerField(default=0, verbose_name='Excel文件大小(字节)')),
                ('pdf_filename', models.CharField(blank=True, max_length=255, null=True, verbose_name='PDF文件名')),
                ('pdf_content', models.TextField(blank=True, null=True, verbose_name='PDF文件内容(Base64)')),
                ('pdf_size', models.IntegerField(default=0, verbose_name='PDF文件大小(字节)')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '选型记录',
                'verbose_name_plural': '选型记录',
                'db_table': 'selection_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='selectionrecord',
            index=models.Index(fields=['project_name'], name='selection_r_project_4e4c72_idx'),
        ),
        migrations.AddIndex(
            model_name='selectionrecord',
            index=models.Index(fields=['selection_type'], name='selection_r_selecti_12e23f_idx'),
        ),
        migrations.AddIndex(
            model_name='selectionrecord',
            index=models.Index(fields=['-created_at'], name='selection_r_created_90e7f2_idx'),
        ),
    ]

