import React, { useState } from 'react';
import {
  Card,
  Button,
  Select,
  DatePicker,
  Space,
  Divider,
  Typography,
  Row,
  Col,
  Statistic,
  message,
  Spin,
} from 'antd';
import {
  FileTextOutlined,
  FilePdfOutlined,
  FileExcelOutlined,
  ProjectOutlined,
} from '@ant-design/icons';
import { useProject } from '../contexts/ProjectContext';
import { logger } from '../utils/logger';
import jsPDF from 'jspdf';
import * as XLSX from 'xlsx';

const { Title, Text } = Typography;
const { RangePicker } = DatePicker;

const ReportGenerator: React.FC = () => {
  const { currentProject } = useProject();
  const [reportType, setReportType] = useState<string>('progress');
  const [dateRange, setDateRange] = useState<any>(null);
  const [isGenerating, setIsGenerating] = useState(false);

  const reportTypes = [
    { value: 'progress', label: '📊 项目进度报告', icon: <FileTextOutlined /> },
    { value: 'cost', label: '💰 成本分析报告', icon: <FileTextOutlined /> },
    { value: 'device', label: '🔧 设备采购报告', icon: <FileTextOutlined /> },
    { value: 'safety', label: '🛡️ HSE安全报告', icon: <FileTextOutlined /> },
    { value: 'summary', label: '📈 项目总结报告', icon: <FileTextOutlined /> },
  ];

  const generatePDF = async () => {
    if (!currentProject) {
      message.warning('请先选择项目');
      return;
    }

    setIsGenerating(true);
    message.loading('正在生成PDF报告...', 0);

    setTimeout(() => {
      try {
        const pdf = new jsPDF();

        // 标题
        pdf.setFontSize(20);
        pdf.text('EPC Project Report', 20, 20);

        pdf.setFontSize(12);
        pdf.text(`Project: ${currentProject.name}`, 20, 35);
        pdf.text(
          `Report Type: ${reportTypes.find((t) => t.value === reportType)?.label || ''}`,
          20,
          45
        );
        pdf.text(`Generated: ${new Date().toLocaleString()}`, 20, 55);

        pdf.line(20, 60, 190, 60);

        // 项目信息
        pdf.setFontSize(14);
        pdf.text('Project Information', 20, 75);
        pdf.setFontSize(10);
        pdf.text(`Project ID: ${currentProject.id}`, 25, 85);
        pdf.text(`Status: ${currentProject.status}`, 25, 95);
        pdf.text(`Progress: ${currentProject.progress}%`, 25, 105);
        pdf.text(`Manager: ${currentProject.manager || 'N/A'}`, 25, 115);

        // 进度概览
        pdf.setFontSize(14);
        pdf.text('Progress Overview', 20, 135);
        pdf.setFontSize(10);
        pdf.text(`Start Date: ${currentProject.start_date || 'N/A'}`, 25, 145);
        pdf.text(`End Date: ${currentProject.end_date || 'N/A'}`, 25, 155);
        pdf.text(
          `Budget: ${currentProject.budget ? `¥${currentProject.budget.toLocaleString()}` : 'N/A'}`,
          25,
          165
        );

        // 统计数据
        pdf.setFontSize(14);
        pdf.text('Statistics', 20, 185);
        pdf.setFontSize(10);
        pdf.text('Tasks Completed: 23/45', 25, 195);
        pdf.text('Devices Installed: 67/89', 25, 205);
        pdf.text('Safety Inspections: 156', 25, 215);
        pdf.text('Quality Tests Passed: 234/240', 25, 225);

        // 备注
        pdf.setFontSize(8);
        pdf.text('Generated by EPC Project Management System v2.0.0-zxx', 20, 280);

        pdf.save(`${currentProject.name}-${reportType}-${Date.now()}.pdf`);

        message.destroy();
        message.success('PDF报告生成成功！');
      } catch (error) {
        message.destroy();
        message.error('PDF生成失败');
        logger.error('[报表生成] PDF生成失败:', error);
      } finally {
        setIsGenerating(false);
      }
    }, 1500);
  };

  const generateExcel = async () => {
    if (!currentProject) {
      message.warning('请先选择项目');
      return;
    }

    setIsGenerating(true);
    message.loading('正在生成Excel报告...', 0);

    setTimeout(() => {
      try {
        const wb = XLSX.utils.book_new();

        // 项目概览表
        const projectData = [
          ['项目信息报告'],
          [''],
          ['项目名称', currentProject.name],
          ['项目编号', currentProject.id],
          ['项目状态', currentProject.status],
          ['项目进度', `${currentProject.progress}%`],
          ['项目经理', currentProject.manager || '-'],
          ['开始日期', currentProject.start_date || '-'],
          ['结束日期', currentProject.end_date || '-'],
          ['项目预算', currentProject.budget || '-'],
          [''],
          ['生成时间', new Date().toLocaleString()],
        ];
        const ws1 = XLSX.utils.aoa_to_sheet(projectData);
        XLSX.utils.book_append_sheet(wb, ws1, '项目概览');

        // 进度统计表
        const progressData = [
          ['类型', '完成数量', '总数量', '完成率'],
          ['施工任务', '23', '45', '51%'],
          ['设备安装', '67', '89', '75%'],
          ['安全检查', '156', '160', '97%'],
          ['质量检测', '234', '240', '97%'],
        ];
        const ws2 = XLSX.utils.aoa_to_sheet(progressData);
        XLSX.utils.book_append_sheet(wb, ws2, '进度统计');

        // 设备清单表
        const deviceData = [
          ['设备名称', '规格型号', '状态', '安装日期', '负责人'],
          ['离心泵P-101', 'IS80-50-200', '已安装', '2024-01-15', '张工'],
          ['换热器E-201', 'BEM400-1.6-200-4/25', '待安装', '-', '李工'],
          ['反应釜R-301', 'GSH-5000', '已安装', '2024-02-20', '王工'],
          ['压缩机C-401', 'L-40/8', '运输中', '-', '赵工'],
        ];
        const ws3 = XLSX.utils.aoa_to_sheet(deviceData);
        XLSX.utils.book_append_sheet(wb, ws3, '设备清单');

        XLSX.writeFile(wb, `${currentProject.name}-${reportType}-${Date.now()}.xlsx`);

        message.destroy();
        message.success('Excel报告生成成功！');
      } catch (error) {
        message.destroy();
        message.error('Excel生成失败');
        logger.error('[报表生成] Excel生成失败:', error);
      } finally {
        setIsGenerating(false);
      }
    }, 1500);
  };

  return (
    <div>
      <Title level={2}>
        <FileTextOutlined /> 项目报表生成
      </Title>
      <Text type="secondary">快速生成各类项目报表，支持PDF和Excel格式导出</Text>

      <Divider />

      {!currentProject ? (
        <Card>
          <Space direction="vertical" align="center" style={{ width: '100%', padding: 40 }}>
            <ProjectOutlined style={{ fontSize: 48, color: '#ccc' }} />
            <Text type="secondary">请先在页面顶部选择一个项目</Text>
          </Space>
        </Card>
      ) : (
        <>
          <Row gutter={[16, 16]}>
            <Col span={24}>
              <Card title="当前项目" variant="borderless">
                <Row gutter={16}>
                  <Col span={6}>
                    <Statistic
                      title="项目名称"
                      value={currentProject.name}
                      valueStyle={{ fontSize: 16 }}
                    />
                  </Col>
                  <Col span={6}>
                    <Statistic title="项目进度" value={currentProject.progress} suffix="%" />
                  </Col>
                  <Col span={6}>
                    <Statistic
                      title="项目状态"
                      value={currentProject.status}
                      valueStyle={{ fontSize: 16 }}
                    />
                  </Col>
                  <Col span={6}>
                    <Statistic
                      title="项目预算"
                      value={currentProject.budget || 0}
                      prefix="¥"
                      precision={0}
                    />
                  </Col>
                </Row>
              </Card>
            </Col>

            <Col span={24}>
              <Card title="报表配置" variant="borderless">
                <Space direction="vertical" size="large" style={{ width: '100%' }}>
                  <div>
                    <Text strong>报表类型</Text>
                    <Select
                      value={reportType}
                      onChange={setReportType}
                      style={{ width: '100%', marginTop: 8 }}
                      size="large"
                      options={reportTypes}
                    />
                  </div>

                  <div>
                    <Text strong>时间范围（可选）</Text>
                    <RangePicker
                      value={dateRange}
                      onChange={setDateRange}
                      style={{ width: '100%', marginTop: 8 }}
                      size="large"
                    />
                  </div>
                </Space>
              </Card>
            </Col>

            <Col span={24}>
              <Card title="导出报表" variant="borderless">
                <Spin spinning={isGenerating}>
                  <Space
                    size="large"
                    style={{ width: '100%', justifyContent: 'center', padding: 20 }}
                  >
                    <Button
                      type="primary"
                      size="large"
                      icon={<FilePdfOutlined />}
                      onClick={generatePDF}
                      disabled={isGenerating}
                      style={{ width: 200, height: 80, fontSize: 16 }}
                    >
                      生成PDF报告
                    </Button>
                    <Button
                      type="primary"
                      size="large"
                      icon={<FileExcelOutlined />}
                      onClick={generateExcel}
                      disabled={isGenerating}
                      style={{
                        width: 200,
                        height: 80,
                        fontSize: 16,
                        background: '#52c41a',
                        borderColor: '#52c41a',
                      }}
                    >
                      生成Excel报告
                    </Button>
                  </Space>
                </Spin>
              </Card>
            </Col>
          </Row>
        </>
      )}
    </div>
  );
};

export default ReportGenerator;
